url=stratum+tcp://us.icminers.com:9160
user=3cUq7e2scUmfZYsPTndakWSmjihxTWrEqjD7isyRTQK1AjtKNMpGY.worker1
pass=x
device=0
batch=16777216
threads=256
nonce-bytes=24
nonce-sans-bytes=22
nonce-mode=prepend
target-order=be
